### ISSUE TITLE
package request

### ISSUE THREAD

**Issue by solitudealma** [Benex254/FastAnime#11]
Since nix is ​​used to provide the development environment, why not provide the installation method of nix, or package it into nur

**Comment by Benex254** [comment]
I am still very new to nixos (literally less than  week in) and was basically helped by chatgpt to write that. I still use uv for dev env since it still works well with nix. And only shell.nix works flake.nix doesn't. Would appreciate it if you could contribute to making this possible

**Comment by she11sh0cked** [comment]
You can definitely already use the [flake](https://github.com/Benex254/FastAnime/blob/master/flake.nix) provided by this project :)
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    fastanime = {
      url = "github:Benex254/fastanime";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      nixpkgs,
      home-manager,
      ...
    }@inputs:
    let
      pkgs = import nixpkgs { system = "x86_64-linux"; };
    in
    {
      homeConfigurations.username = home-manager.lib.homeManagerConfiguration {
        inherit pkgs;
        modules = [
          {
            home.packages = [
              inputs.fastanime.packages.${pkgs.system}.default
            ];
          }
        ];
      };
    };
}
```

**Comment by Benex254** [comment]
I am still very new to nixos and would prefer someone more experience to do it for me. Though the flake works and you can do `nix profile install github:Benex254/fastanime`,  Thats sth i put together with the aid of chatgpt. Though @KaylorBen  said they might finish it for me and has also updated it to make it work,
