### ISSUE TITLE
uv installation instructions slightly incorrect

### ISSUE THREAD

**Issue by AtticusHelvig** [Benex254/FastAnime#12]
uv cannot find the packages (at least for me, I had not used uv before this) if they are not surrounded by double quotes.

[Source](https://docs.astral.sh/uv/pip/packages/)

**README** currently reads:

```bash
# generally:
uv tool install fastanime[standard]

# or stripped down installations:
uv tool install fastanime
uv tool install fastanime[api]
uv tool install fastanime[mpv]
uv tool install fastanime[notifications]
```

Should be:

```bash
# generally:
uv tool install "fastanime[standard]"

# or stripped down installations:
uv tool install fastanime
uv tool install "fastanime[api]"
uv tool install "fastanime[mpv]"
uv tool install "fastanime[notifications]"
```

**Comment by Benex254** [comment]
hmmm, what shell are you using cause i used the same command or is this windows. Anyways you are right it probably a good idea to quote it. Can you make the changes and submit a pr

**Comment by AtticusHelvig** [comment]
I'm using `zsh` on arch. Pull request [here](https://github.com/Benex254/FastAnime/pull/16).
