### ISSUE TITLE
invalid color specification: label:#aeaeae

### ISSUE THREAD

**Issue by piradata** [Benex254/FastAnime#14]
![image](https://github.com/user-attachments/assets/ecad5d28-d897-4125-8966-38bc7c68cb94)

**Comment by piradata** [comment]
seems to be enabling fzf the problem

**Comment by Benex254** [comment]
First of all yo used an incomplete command to update your config.` It should be fastanime --fzf --icons config --update`. That error also looks familiar check the version of fzf you are running it should be 0.56.0

**Comment by piradata** [comment]
i was on 0.29 🙃 fuck ubuntu and his "will never update anything" policy
