### ISSUE TITLE
unknown action: toggle-wrap

### ISSUE THREAD

**Issue by Shouri14** [Benex254/FastAnime#18]
First of all, thank you for developing this, like it very much. Very clean.

I'm facing this particular issue only when using `--preview` with `--fzf`.
To reproduce: `fastanime --icons --preview --fzf anilist`

![image](https://github.com/user-attachments/assets/da9770ba-1077-47cf-9b7f-22664e326509)

Extra Context:
- Using `Windows 11`
- Terminal -> `Terminal Preview app` from windows store
- Installed using `pip`

**Comment by Benex254** [comment]
Welcome. This looks like a fzf version issue, check if its 0.56.0

**Comment by Shouri14** [comment]
> Welcome. This looks like a fzf version issue, check if its 0.56.0

That was the problem. Upgrading fzf, resolve it.
Seeing a different issue, but will open another thread for that. Thanks.

**Comment by Benex254** [comment]
Join the discord
