### ISSUE TITLE
[bug] only output the completions

### ISSUE THREAD

**Issue by she11sh0cked** [Benex254/FastAnime#21]
Currently when you run the completions subcommand it will output the completions and some logs:
```sh
$ fastanime completions
Checking for updates...
So you can enjoy the latest features and bug fixes
You can disable this by setting check_for_updates to False in the config

<actual completions>
```

This however is problematic when you want to load the completions with an eval:
```sh
eval "$(fastanime completions)"
```

A workaround for this is to cut the first 3 lines of the output:
```sh
eval "$(fastanime completions | tail -n +4)"
```

**Comment by Benex254** [comment]
hmm, forgot it would affect that, maybe the info for checking for update should be printed to stderr instead of stdout. Would you like to tackle this one?

**Comment by she11sh0cked** [comment]
I could certainly try this evening :) But wouldn't it be better to just skip the check for the completions subcommand?

**Comment by Benex254** [comment]
If you can implement it that way fine by me.
