### ISSUE TITLE
chafa image not displaying

### ISSUE THREAD

**Issue by gand0rf** [Benex254/FastAnime#22]
Hello. I came across your tool yesterday and really like it so far. I did come across an issue where when selecting 'View Info', it did not show the image. Everything else displayed just fine. I am still learning git and not sure how to setup a pull request, so thought to open an issue ticket as it is a easy fix.

File with issue: fastanime/cli/utils/print_img.py

Current line 27:
```
subprocess.run([EXECUTABLE, url, "--size=15x15"], input=img_bytes)
```

Suggested fix for line 27:
```
subprocess.run([EXECUTABLE, "--size=15x15"], input=img_bytes)
```

Yeah, all that seems to need to be done is to remove url from the command.

I reached out to the chafa dev after test the chafa command on my sytem. Link to issue ticket with explanation: https://github.com/hpjansson/chafa/issues/233

System Info:
Xubuntu 24
kitty 0.37.0

**Comment by Benex254** [comment]
Never touched that file (2mnths ago) in a while :laughing: . Thanks, will update it later. Though i think if you try doing it yourself it would not be as hard as you imagine. So give it a try before saying you can't do it.

**Comment by Benex254** [comment]
I'have written more than enough (13k+) solo. Its time for the community to step up.  So, I'll will be waiting for your pr :laughing:

**Comment by gand0rf** [comment]
Sure!! At the gym and just found a vid that made it 100x more clear on how to do it then the docs do. Will make it when I get home.

**Comment by gand0rf** [comment]
PR put in https://github.com/Benex254/FastAnime/pull/24

**Comment by Benex254** [comment]
Merged, told you could do it
