### ISSUE TITLE
[feature] use fzf environment variables before overwritting with defaults

### ISSUE THREAD

**Issue by voidlesity** [Benex254/FastAnime#26]
right now fastanime will overwrite any existing fzf configuration that is set in the environment rendering 

would be cool if the program would first check if any env variables are set before overwriting with defaults

**Comment by Benex254** [comment]
The fzf opts are now defined in the config file. I recommend deleting your existing config file so you can also get the notes on how to set it up. And join the discord to stay upto date

**Comment by voidlesity** [comment]
I am aware that they are now defined there but what if I have existing configuration in the env for fzf it will just get overwritten just a small check if they are defined or not would be enough

you can reject my pull request if it doesn't fit though
https://github.com/Benex254/FastAnime/pull/27

:3

**Comment by Benex254** [comment]
Its in the config file for convinience so you can like push it to github along with your other dotfiles and initially if you look at the code and commit history thats what i was doing  only recently have I updated it to be defined in you config file (1dy ago).
I still believe its convinient that why. 
Just delete your existing config file and see how its setup
you can even define a custom header ascii art now 
Hope you like the new way :smile:

**Comment by Benex254** [comment]
Oh and plus if you want your existing fzf env to be used by fastanime just paste it in your config file
