### ISSUE TITLE
filename.unknown_video file extension

### ISSUE THREAD

**Issue by watermelvin** [Benex254/FastAnime#5]
Some downloads result in a .unknown_video rather than a .mp4. renaming files manually fixes the issue, and it doesn't stop mpv playback, but it is annoying.
![image](https://github.com/user-attachments/assets/501dd3d8-c1b8-4bba-b3ca-b7a55ebb95a1)

**Comment by Benex254** [comment]
Yeah been ignoring that one for sometime. Its caused by yt-dlp when it can't figure out an appropriate extension. This is because yt server of allanime gives direct links making it hard to infer the extension . Anyway its fixed in the latest commits.
